### ISSUE TITLE
pip install fails due to dependency on PIL

### ISSUE THREAD

**Issue by wovano** [ReneTC/sgraphic#1]
When I run run `pip install sgraphic`, it fails to install version 0.1.1 and falls back to version 0.0.3:

```pip install sgraphic==0.1.1
Collecting sgraphic==0.1.1
  Using cached sgraphic-0.1.1.tar.gz (4.4 kB)
Collecting skia-python
  Using cached skia_python-87.2-cp39-cp39-win_amd64.whl (4.3 MB)
Collecting IPython
  Using cached ipython-7.27.0-py3-none-any.whl (787 kB)
ERROR: Could not find a version that satisfies the requirement PIL (from sgraphic) (from versions: none)
ERROR: No matching distribution found for PIL
```

The dependency of your package lists "PIL", but as far as I know the package that contains PIL is called Pillow. Is it possible that this is just a typo in your dependency list?

**Comment by ReneTC** [comment]
Thank you very much for taking the time to help me! It finally work after trying your suggestion
